"""empty message

Revision ID: da0734edaa78
Revises: 
Create Date: 2021-10-25 00:20:31.839518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0734edaa78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MoviesAndActors',
    sa.Column('Movie_id', sa.Integer(), nullable=True),
    sa.Column('Actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Actor_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['Movie_id'], ['actor.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MoviesAndActors')
    op.drop_table('movie')
    op.drop_table('actor')
    # ### end Alembic commands ###
